import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <nav className={styles.main_nav}>
                    <ul>
                        <li>A</li>
                        <li>B</li>
                        <li>C</li>
                    </ul>
                </nav>

                <section className={styles.main_content}>
                    <img className={styles.user} src={`/oscar.jpg`}/>
                    <h1 className={styles.title}>
                        Oscar Javier Campos Herrera
                    </h1>
                    <ul className={styles.social_links}>
                        <li>
                            <a target="_blank" rel="noreferrer" href="https://www.linkedin.com/in/oscar-camposh/" >
                                <img src="/linkedin.svg" alt=""/>
                            </a>
                        </li>
                        <li>
                            <a target="_blank" rel="noreferrer" href="https://github.com/w0nde">
                                <img src="/github.svg" alt=""/>
                            </a>
                        </li>
                        <li>
                            <a target="_blank" rel="noreferrer" href="https://github.com/w0nde">
                                <img src="/youtube.svg" alt=""/>
                            </a>
                        </li>
                    </ul>
                    <di className={styles.technologies}>
                        <h2>Technologies</h2>
                        <ul>
                            <li>Java - Spring Boot</li>
                            <li>Python</li>
                            <li>Nodejs, Go</li>
                            <li>Angular</li>
                            <li>React</li>
                            <li>AWS</li>
                            <li>Docker</li>
                            <li>Kubernetes</li>
                            <li>Linux</li>
                            <li>Nginx</li>
                        </ul>
                    </di>
                </section>
            </main>

            <footer className={styles.footer}>
                <a rel="noopener noreferrer">

                </a>
            </footer>
        </div>
    )
}
